### ISSUE TITLE
improve handling of special chars in mysql passwords

### ISSUE THREAD

**Issue by brutus** [Uberspace/takeout#27]
E.g. `%` leads to 

```
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%§ # NICHT ÄNDERN, ohne den obigen Text zu lesen!'
```

Also consider handling quotationmarks (smarter).

**Comment by nichtmax** [comment]
Same with `Ä`

**Comment by SalocinHB** [comment]
> Jonas Pasche  < 1 minute ago
> Ich rege hier mal an, my_print_defaults via Shell zu verwenden, statt ConfigParser. Die .my.cnf ist halt nur so uuungefähr eine Datei im Format, das ConfigParser erwartet.

**Comment by jonmz** [comment]
The `%` problem could be solved using `ConfigParser(interpolation=None)`.

**Comment by brutus** [comment]
https://github.com/Uberspace/takeout/pull/29

**Comment by brutus** [comment]
https://github.com/Uberspace/takeout/pull/29
