### ISSUE TITLE
some MySQL passwords contain #

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/takeout#37]
Do not assume `#` is a comment in `password = …` lines in `~/.my.cnf`.

https://github.com/Uberspace/takeout/blob/48f38840a986657027394549f41f3aa488a7da01/uberspace_takeout/items/common.py#L67

**Comment by luto** [comment]
https://github.com/Uberspace/takeout/commit/7409ddf1a4a3d03e07220373eab215660a9b1bf8
